#!/bin/bash

TEMPDIR=$(mktemp -dt XXXXXXXX)
HOMET="${HOME}/t"

if [[ -e "${HOMET}" ]] ; then
    if [[ -h "${HOMET}" ]] ; then
        rm -f "${HOMET}"
        ln -s "${TEMPDIR}" "${HOMET}"
    else
        echo "${HOMET} exists and is not a symlink."
    fi
else
    if [[ -h "${HOMET}" ]] ; then
        # This happens if it's a dead symlink
        rm -f "${HOMET}"
    fi
    ln -s ${TEMPDIR} ${HOMET}
fi

cd ${TEMPDIR}
